defaults:
  - base.yaml
  - model.yaml

datasets:
  - lakh_full

training:
  epochs: 1

dataloader:
  batch_size: 128
  shuffle: true

optimizer:
  name: AdamW
  lr: 0.0005
  weight_decay: 0.01

loss:
  independent_instrument_activation_supervision: True
  kl_max_weight: 0.05


